### ISSUE TITLE
Deprecated methods

### ISSUE THREAD

**Issue by cdnfreelancer** [patilswapnilv/login-and-logout-redirect#1]
I am running your plugin on the current version of Wordpress and I am getting the following error:

Strict Standards: Redefining already defined constructor for class Logout_Redirect in /home/adept/domains/fkkc.org/public_html/wp-content/plugins/login-and-logout-redirect/login-and-logout-redirect.php on line 44

Deprecated: Assigning the return value of new by reference is deprecated in /home/adept/domains/fkkc.org/public_html/wp-content/plugins/login-and-logout-redirect/login-and-logout-redirect.php on line 203

Strict Standards: Redefining already defined constructor for class Login_Redirect in /home/adept/domains/fkkc.org/public_html/wp-content/plugins/login-and-logout-redirect/login-and-logout-redirect.php on line 221

Deprecated: Assigning the return value of new by reference is deprecated in /home/adept/domains/fkkc.org/public_html/wp-content/plugins/login-and-logout-redirect/login-and-logout-redirect.php on line 322

**Comment by patilswapnilv** [comment]
@cdnfreelancer Can you explain how I can recreate this. I tried it on my setup, vagrant VVV and it worked fine. Also I would suggest using the repo from wordpress.org/plugins/login-and-logout-redirect/

on github this is a continuous development repo, the wordpress.org is a stable release.

**Comment by cdnfreelancer** [comment]
All I did was install the plugin through the Wordpress control panel.

Trying the github code.
