### ISSUE TITLE
Redirect After Second Login

### ISSUE THREAD

**Issue by griffinassoc** [patilswapnilv/login-and-logout-redirect#4]
Hi,

The plugin works correctly the a user logs into the site. However, if the user logs out and then immediately logs back in they're being redirected to the Admin area instead of the URL listed in the plugin.

Here's an example of the url after they first log out. Notice there's a redirect being included in the URL:

https://[DOMAINNAME].com/wp-login.php?redirect_to=https%3A%2F%2F[DOMAINNAME]%2Fwp-admin%2F&reauth=1

Any ideas?

**Comment by patilswapnilv** [comment]
Hey @griffinassoc,

I saw this happen only if the user uses the back button. Considering the usecase, you can redirect the users on logout to a different location from the regular login screen after logout. 

Please let me know if you still face any issues.
