### ISSUE TITLE
Logout to "/" isn't working

### ISSUE THREAD

**Issue by martinarean** [patilswapnilv/login-and-logout-redirect#5]
Hi, when the user login i set a custom page to redirect and that works fine, but when I try to redirect to home on logout it stays on current page.

My config:
![screen shot 2017-10-23 at 10 36 40](https://user-images.githubusercontent.com/19198031/31891912-13e617b0-b7de-11e7-89b5-ad49f637b2ac.png)

My active plugins:
[Plugins ‹ Ajedrez del Sur — WordPress.pdf](https://github.com/patilswapnilv/login-and-logout-redirect/files/1407298/Plugins.Ajedrez.del.Sur.WordPress.pdf)

Thanks!

**Comment by patilswapnilv** [comment]
Hello @martinarean, 
Thank you for reporting the issue. 

I just tested the plugin on my development env. It does give issues when I don't use `http://` or `https://`. But when I use them, it works perfectly well for me. 

I see that you are using multiple plugins, could you please run a plugin conflict test, so I can know what exactly is causing this on your site?
This blog post on Yoast explains how to perform a plugin conflict well, just replace the Yeost SEO plugin with Login and logout redirect. https://kb.yoast.com/kb/how-to-check-for-plugin-conflicts/

Hope this helps, 

Regards, 
Swapnil

**Comment by martinarean** [comment]
Hi @patilswapnilv, thanks for your answer.

I followed your adivice and the result is that the conflict is with my theme (Kleo-https://seventhqueen.com/themes/kleo/).

Any idea?

Regards
