### ISSUE TITLE
Redirecting links to login page

### ISSUE THREAD

**Issue by bbonjui** [patilswapnilv/login-and-logout-redirect#6]
Hi,
thanks for the plugin. works well for what i want...as its name suggests.
Installed, added login url on its text box in Settings. (thats all i did).

but when clicking on a link to a post, it redirects to the login page
please confirm if there is a fix
regards
Bradley

**Comment by patilswapnilv** [comment]
@bbonjui Sorry for really late response. I have tested the plugin with WP version 4.9.8 and found no issues. 
Closing this. 
Please let me know if you still see any issues.
